<Project Sdk="MSTest.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <!--
      The MSTest runner displays test failures in the console as well as the TRX report.
      Detailed diagnostic logging can have a performance impact.
      For more information, visit https://learn.microsoft.com/dotnet/core/testing/unit-testing-platform-integration-dotnet-test#show-failure-per-test
    -->
    <EnableMicrosoftTestingExtensionsCodeCoverage>false</EnableMicrosoftTestingExtensionsCodeCoverage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClutterFlock.csproj" />
    <PackageReference Include="coverlet.MTP" Version="10.0.1" />
  </ItemGroup>
</Project>
